---
formatter: markdown

content: |-
  {%- raw %}
  {{ .Header }}

  {{ .Footer }}

  {{ .Inputs }}

  {{ .Modules }}

  {{ .Outputs }}

  {{ .Providers }}

  {{ .Requirements }}

  {{ .Resources }}
  {%- endraw %}

output:
  file: README.md
  mode: inject
  template: |-
    {%- raw %}
    [//]: # (BEGIN_TF_DOCS)

    {{ .Content }}

    [//]: # (END_TF_DOCS)
    {%- endraw %}

recursive:
  enabled: false

settings:
  hide-empty: true
